version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: book_db

  rustapi:
    container_name: rustapi
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
