version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      # POSTGRES_DB: za_vahiny
    volumes:
        - postgres-data:/var/lib/postgresql/data    

  rustapi:
    container_name: rustapi
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    # volumes:
    #   - ./backend:/server
    #   - cargo-cache:/usr/local/cargo/registry
    #   - target-cache:/app/target  
    # command: /bin/sh -c "cargo watch -x run"

volumes:
  postgres-data:
#     cargo-cache:
#     target-cache:    

  


