# Use rust image as base for both stages 
FROM rust:1.75-buster as builder

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y libpq5 libpq-dev libssl-dev pkg-config

# Install cargo-watch
RUN cargo install cargo-watch

# Build application 
COPY . .

RUN cargo build --release

# Production stage
FROM debian:buster-slim

# In the production stage  
WORKDIR /usr/local/bin

# Install dependencies
RUN apt-get update && apt-get install -y libpq5 libssl-dev pkg-config

# Copy cargo-watch from builder
COPY --from=builder /usr/local/cargo/bin/cargo-watch .

# Copy application
COPY --from=builder /app/target/release/server .

# Run app
CMD ["./server"]